using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace CreateTVSeriesDatabase.Models
{

    // generated by EDIT->Paste Special->AS JSON class with JSON class in paste buffer
    // what an cool feature

    // --------------- ACTORS --------------------- nm=1 
    public class PersonRootobject
    {
        public Name[] name_popular { get; set; }
        public Name[] name_exact { get; set; }
        public Name[] name_approx { get; set; }
    }

    public class Name
    {
        public string id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }

    // --------------- TITLES --------------------- tt=1 

    public class TitleRootobject
    {
        public Title[] title_popular { get; set; }
        public Title[] title_exact { get; set; }
        public Title[] title_approx { get; set; }
    }

    public class Title
    {
        public string id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string title_description { get; set; }
        public string episode_title { get; set; }
        public string description { get; set; }
    }

}
